# Builds SemTK upon every push (but ignoring tag-only pushes):
#  - Builds SemTK sources
#  - Runs code analysis scan (TBD)

name: SemTK continuous build

on:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v2

    - name: Build SemTK jars
      # TODO: The tests currently fail in Github Actions
      run: |
        mvn -version
        mvn -B install -DskipTests
