# Builds SemTK upon every push:
#  - Caches Maven repository needed to build SemTK
#  - Builds SemTK sources
#  - Runs code analysis scan (TBD)

name: SemTK continuous build

on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v2

    - name: Run Maven build
      # TODO: The tests currently fail in Github Actions.
      run: |
        mvn -version
        mvn -B install -DskipTests
