# Builds SemTK distribution tarball when a release is published:
#  - Caches Maven repository needed to build SemTK
#  - Builds SemTK sources
#  - Uploads SemTK distribution tarball to GitHub release page

name: SemTK release build

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven

# TODO: The tests currently fail in Github Actions.
    - name: Run Maven build
      run: mvn -B install -DskipTests

    - name: Upload SemTK distribution tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: distribution/target/semtk-opensource-dist.tar.gz
        asset_name: semtk-opensource-${{ github.event.release.tag_name }}-dist.tar.gz
        asset_content_type: application/gzip
