# Builds SemTK dist tarball when a release is published:
#  - Builds SemTK sources
#  - Uploads SemTK dist tarball to GitHub release page

name: SemTK release build

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v2

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/pom.xml') }}

    - name: Build SemTK release
      run: |
        mvn -version
        mvn install -DskipTests -Prelease

    - name: Upload SemTK dist tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: distribution/target/semtk-opensource-dist.tar.gz
        asset_name: semtk-opensource-${{ github.event.release.tag_name }}-dist.tar.gz
        asset_content_type: application/gzip
